version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        restart: always
        volumes:
            - ./:/var/www
        networks:
            - location
    pg_db:
        image: timescale/timescaledb:latest-pg11
        container_name: pg_db
        hostname: pg_db
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: location
        volumes:
            - local_pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        expose:
            - 5432
        networks:
            - location
networks:
    location:
        driver: bridge

volumes:
    local_pgdata:
